### PR TITLE
Extensions

### PR DESCRIPTION
**Pull request by racerxdl**
I added some extensions to Seq library and I check that there is some unsafe uses here. For example the constructors are not consistent: One of them creates a internal array and adds all the elements, the other one sets the internal list to the external list.

A more dangerous thing is that the method toArrayList casts the internal list to ArrayList, but it can be any other type of list.

So because of that, I would suggest the Seq<T> class be abstract (like the List<T> class is) and only use implementations like ArraySeq and LinkedSeq. In this way it should be safer.

So everything that I thing it shouldn't be there (or is wrong) it is annotated as Deprecated. In this way a new library wont break current existing codes but will warn the developers that they need to change the uses.

Also there are other changes I did:
-   Changed `add` method on Seq class to return boolean to conform to Collections standard.
-   Added `addAll` method on Seq Class
-   Added missing stuff in JavaDoc
-   Added missing `<>` to Seq initialization (initializing by new Seq() is not safe)
-   Changed `empty` method to `isEmpty` to conform java Getter / Setter standard
-   The `difference` function were doing nothing. So I changed to be a difference between two Seq (A - B)
-   The method `toArrayList` casted the current list to ArrayList. This is not safe because:
  1. The `this.list` can be **not** ArrayList ( Constructor Seq(List<T>)
  2. You're sharing a internal instance with external code.
-   Added `ArraySeq` and `LinkedSeq` for safe use of Seq
-   Added `Deprecated` notations to Seq initializers because the way is implemented is not safe to use.

### CODE REVIEW

**Comment by racerxdl** [comment]
I would like you guys to review the changes and put your opinions @haskellcamargo @mabrasil @vitorprado  @ppamorim @jmonad/admin

**Comment by vitorprado** [comment]
I really like what you did here, there is a lot of unsafe things in the actual code.
but I have a question, why we should create many subclasses just changing the implementation of the internal `List`? If it's really necessary, why we can't keep the use of `Seq` just adding some `creators` just changing this? or we can keep the default using `ArrayList` and provide a creator with a `Supplier` which creates a implementation of list.

something like that:

```
   Seq<String>.from(() -> new Arraylist<String>());
   Seq<String>.default();
```

I think it's more comfortable to keep the use in `Seq` class, particularly I get confused when I need to find an implementation of list to use, but it's just my opinion.

**Comment by racerxdl** [comment]
We can do that @vitorprado , I just suggested the subclasses because it looks more like the Java way (it is not a standard though). In the java way we would do:

```
Seq<String> myArraySeq = new ArraySeq<>();
Seq<String> myLinkedSeq = new LinkedSeq<>();
```

But that is not a standard in any means of java. Also I liked your way, but maybe instead default() we just use the standard constructor, something like this

```
Seq<String> myArraySeq = new Seq<>();
Seq<String> myLinkedSeq = Seq<>.withLinkedList();
```

What do you think about?

**Comment by vitorprado** [comment]
I think we can use one way to construct the Seq, just one. I think it's more simple to use.
If you look into Optional in java 8 you find a "default" constructor called "of()" I think it's so simple and concise, when you need to create the object you just need one, only one, method "of()". (ok you have another `constructors` to create empty object, etc)

just an example:

```
Seq.with(ArrayList::new);
Seq.with(LinkedList::new);
```

When you have one method to create the object and a default public constructor too, you give 2 ways of creating the object, and when I use something I want to have one way to do it. 
Or we can hide the default and just have a `with` constructor and forget the `default` creation with `ArrayList` and ask for a implementation of `List` in every instance.

It's just a guess, what do you think about @racerxdl ?

**Comment by racerxdl** [comment]
I agree @vitorprado. I liked this solution. When I get home I will change this PR code to match this spec.

**Comment by racerxdl** [comment]
So I was taking a look now in the issue, and I found that is a bigger issue than I tough.
The way the Java 8 optionals use the .of is by using a reflection type from the parameter class. This is a good solution, but considering that we want this library to be java universal, and Android doesn't like much Reflection stuff (it should be avoided at maximum) I would prefer to keep reflection of limits for this library.

Considering that, for now I fixed to ArrayList the default implementation (that will work fine for almost all cases) and then we can check it later.

**Comment by vitorprado** [comment]
Damn Android, reflection is so awesome :/
It's fine. 👍 👍  :shipit: 

We can discuss more about this problem.
Thanks a lot @racerxdl

**Comment by vitorprado** [comment]
I thinks it's really important. Can we merge it? @ppamorim @racerxdl @haskellcamargo

**Comment by racerxdl** [comment]
For me it is ok. @ppamorim and @haskellcamargo have you checked the code?

**Comment by racerxdl** [comment]
Ok so they confirmed on Facebook that they approve. I'm merging it.

**Pull request merged**
